name: Price Tracker Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1-31/2 * *'
  workflow_dispatch:

jobs:
  price-tracker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run Price Tracker
        run: node price-tracker.js
      
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f products.csv
          git diff --cached --quiet || git commit -m "Updated products.csv"
          git push